name: spotify_clone
description: A Flutter app which use spotify sdk.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  spotify_sdk: ^2.3.1
  flutter_animate: ^4.2.0+1
  page_transition: ^2.1.0
  fluttertoast: ^8.2.2
  get_storage: ^2.1.1
  quickalert: ^1.0.2
  marquee: ^2.2.3
  spotify: ^0.12.0
  palette_generator: ^0.3.3+3
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.1
  provider: ^6.0.5
  dio: ^4.0.6
  flutter_inappwebview: ^5.8.0
  url_launcher: ^6.2.1
  oauth2: ^2.0.2
  buttons_tabbar: ^1.3.8
  scrollable_positioned_list: ^0.3.8
  audioplayers: ^5.2.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - lib/.env
